# Generated by Django 5.1.4 on 2025-04-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0003_remove_consulta_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10, null=True, verbose_name='Sexo')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono contacto:')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pacientes/imgs/')),
                ('motivo_consulta', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo de consulta')),
                ('objetivos', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Objetivos')),
                ('consultas', models.ManyToManyField(blank=True, related_name='pacientes', to='consultas.consulta')),
            ],
        ),
    ]
