# Generated by Django 5.1.4 on 2025-04-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_user'),
        ('usuarios', '0002_remove_customuser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'PAC'}, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='usuarios.customuser'),
        ),
    ]
