# Generated by Django 5.1.4 on 2025-04-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='imagen',
        ),
    ]
