# Generated by Django 5.1.4 on 2025-04-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='asignado',
            field=models.BooleanField(default=False, null=True, verbose_name='Asignado'),
        ),
    ]
