# Generated by Django 5.1.4 on 2025-04-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('estado', models.CharField(blank=True, choices=[('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('Agendada', 'Agendada'), ('Confirmada', 'Confirmada')], max_length=255, null=True, verbose_name='Estado')),
                ('motivo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo')),
                ('evolucion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Evolución')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional')),
            ],
        ),
    ]
