# Generated by Django 5.1.4 on 2025-04-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='motivo',
        ),
    ]
