# Generated by Django 5.1.4 on 2025-04-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consulta_paciente'),
        ('profesionales', '0010_alter_profesional_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='profesionales.profesional'),
        ),
    ]
