# Generated by Django 5.1.4 on 2025-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(blank=True, choices=[('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('Agendada', 'Agendada'), ('Confirmada', 'Confirmada'), ('Creada', 'Creada')], default='Creada', max_length=255, null=True, verbose_name='Estado'),
        ),
    ]
