# Generated by Django 5.1.4 on 2025-04-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_consulta_estado'),
        ('pacientes', '0006_alter_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='pacientes.paciente'),
        ),
    ]
