# Generated by Django 5.1.4 on 2025-04-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tipo_atencion', models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Online', 'Online')], max_length=255, null=True, verbose_name='Tipo de Atencion')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono contacto:')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profesionales/imgs/')),
            ],
        ),
    ]
