# Generated by Django 5.1.4 on 2025-04-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='consultas',
            field=models.ManyToManyField(blank=True, related_name='profesionales', to='consultas.consulta'),
        ),
    ]
