# Generated by Django 5.1.4 on 2025-04-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_profesional_consultas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='consultas',
        ),
    ]
