# Generated by Django 5.1.4 on 2025-04-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_remove_profesional_consultas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='telefono',
        ),
    ]
