# Generated by Django 5.1.4 on 2025-04-25 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_remove_profesional_apellido_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='usuarios.customuser'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='tipo_atencion',
            field=models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Online', 'Online')], max_length=20, null=True, verbose_name='Tipo de Atención'),
        ),
    ]
