# Generated by Django 5.1.4 on 2025-04-25 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_alter_profesional_user'),
        ('usuarios', '0002_remove_customuser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='usuarios.customuser'),
        ),
    ]
