# Generated by Django 5.1.4 on 2025-04-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0009_alter_profesional_user'),
        ('usuarios', '0003_customuser_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(limit_choices_to={'asignado': False, 'role': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='usuarios.customuser'),
        ),
    ]
