# Generated by Django 5.1.4 on 2025-04-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0012_disponibilidad_delete_disponibilidadconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
