# Generated by Django 5.1.4 on 2025-04-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0013_alter_disponibilidad_disponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
